; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

monitor_speed = 115200
monitor_filters = time
;monitor_filters = time, log2file
monitor_echo = yes
monitor_port = COM5

lib_deps =
    adafruit/Adafruit RGB LCD Shield Library@1.2.2
    adafruit/Adafruit MCP23017 Arduino Library@2.3.2
    sensirion/arduino-sht@1.2.6
    adafruit/RTClib@2.1.4
    DFRobot/DFRobot_RTU@1.0.6
    DFRobot/DFRobot_RainfallSensor@1.0.0

